/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository:
https://github.com/worldcopyist/obsidian-astrbot-connect
*/

"use strict";var s=Object.defineProperty;var f=Object.getOwnPropertyDescriptor;var m=Object.getOwnPropertyNames;var p=Object.prototype.hasOwnProperty;var r=(o,a)=>{for(var l in a)s(o,l,{get:a[l],enumerable:!0})},u=(o,a,l,e)=>{if(a&&typeof a=="object"||typeof a=="function")for(let d of m(a))!p.call(o,d)&&d!==l&&s(o,d,{get:()=>a[d],enumerable:!(e=f(a,d))||e.enumerable});return o};var x=o=>u(s({},"__esModule",{value:!0}),o);var y={};r(y,{default:()=>n});module.exports=x(y);var c=require("obsidian"),n=class extends c.Plugin{async onload(){}async onunload(){}};
