/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository:
https://github.com/worldcopyist/obsidian-astrbot-connect
*/

"use strict";var t=Object.defineProperty;var p=Object.getOwnPropertyDescriptor;var s=Object.getOwnPropertyNames;var g=Object.prototype.hasOwnProperty;var u=(n,a)=>{for(var l in a)t(n,l,{get:a[l],enumerable:!0})},c=(n,a,l,d)=>{if(a&&typeof a=="object"||typeof a=="function")for(let e of s(a))!g.call(n,e)&&e!==l&&t(n,e,{get:()=>a[e],enumerable:!(d=p(a,e))||d.enumerable});return n};var f=n=>c(t({},"__esModule",{value:!0}),n);var m={};u(m,{default:()=>o});module.exports=f(m);var i=require("obsidian"),o=class extends i.Plugin{async onload(){}async onunload(){}};
